name: she_app
description: SHE App Flutter client
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Networking
  http: ^1.2.0

  # Storage (for real settings)
  shared_preferences: ^2.2.2

  # Location & permissions
  geolocator: ^11.0.0
  location: ^5.0.3
  permission_handler: ^11.3.1

  # Maps
  google_maps_flutter: ^2.6.0

  # UI
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
